"""AutoFile — self-contained YOLO training bundle generated by AutoDetect2.

Unpack on the training machine, point it at the dataset and run:

    python train.py --dataset-root /path/to/dataset

Produces `result/best_<i>.pt` for every model of the ensemble and, unless
`--no-predict` is passed, `submission.csv` with predictions of the best model
over the whole dataset.
"""

from __future__ import annotations

import argparse
import gc
import random
import shutil
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent


def load_yaml(path: Path) -> dict:
    with open(path, "r", encoding="utf-8") as handle:
        return yaml.safe_load(handle) or {}


def remap(entries, root: Path | None) -> list[str]:
    """Re-anchors dataset paths when the bundle runs on another machine."""
    if isinstance(entries, str):
        entries = [entries]
    if root is None:
        return list(entries)

    remapped = []
    for entry in entries:
        parts = Path(entry).parts
        for depth in (3, 2, 1):
            if len(parts) >= depth:
                candidate = root.joinpath(*parts[-depth:])
                if candidate.is_dir():
                    remapped.append(str(candidate))
                    break
        else:
            remapped.append(entry)
    return remapped


def prepare_data(data_path: Path, root: Path | None, workdir: Path) -> Path:
    data = load_yaml(data_path)
    if root is None:
        return data_path

    data["train"] = remap(data.get("train", []), root)
    data["val"] = remap(data.get("val", []) or data["train"], root)
    data.pop("path", None)

    resolved = workdir / "data.resolved.yaml"
    resolved.write_text(yaml.safe_dump(data, allow_unicode=True, sort_keys=False), encoding="utf-8")
    return resolved


def train_params(config: dict) -> dict:
    train = dict(config.get("train", {}))
    augment = dict(config.get("augment", {}))
    runtime = config.get("runtime", {})

    params = {**train, **augment}
    params["workers"] = runtime.get("workers", 4)
    params.pop("imgsz", None)
    return {k: v for k, v in params.items() if v is not None}


def ensemble(config: dict) -> list[tuple[str, str, int]]:
    model = config.get("model", {})
    enabled = [m for m in model.get("ensemble", []) if m.get("enabled")]
    if not enabled:
        enabled = [
            {
                "family": model.get("family", "11"),
                "size": model.get("size", "x"),
                "imgsz": config.get("train", {}).get("imgsz", 960),
            }
        ]
    families = {"8": "yolov8", "11": "yolo11", "12": "yolo12", "26": "yolo26"}
    return [
        (families.get(str(m["family"]), "yolo11"), m.get("size", model.get("size", "x")), int(m.get("imgsz", 960)))
        for m in enabled
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description="AutoDetect2 training bundle")
    parser.add_argument("--data", default=str(HERE / "data.yaml"))
    parser.add_argument("--config", default=str(HERE / "train.yaml"))
    parser.add_argument("--dataset-root", default=None, help="Корень датасета на этой машине")
    parser.add_argument("--output", default=str(HERE / "result"))
    parser.add_argument("--epochs", type=int, default=None)
    parser.add_argument("--device", default=None)
    parser.add_argument("--no-predict", action="store_true")
    args = parser.parse_args()

    import torch
    from ultralytics import YOLO

    config = load_yaml(Path(args.config))
    runtime = config.get("runtime", {})
    seed = int(runtime.get("seed", 42))
    random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

    device = args.device or runtime.get("device", "auto")
    if device == "auto":
        device = 0 if torch.cuda.is_available() else "cpu"

    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)
    root = Path(args.dataset_root).resolve() if args.dataset_root else None
    data_path = prepare_data(Path(args.data), root, output)

    params = train_params(config)
    if args.epochs:
        params["epochs"] = args.epochs
    epochs = params.pop("epochs", 30)

    runs = Path("runs")
    best_models: list[Path] = []

    for index, (family, size, imgsz) in enumerate(ensemble(config)):
        weights = f"{family}{size}.pt"
        print(f"[{index + 1}] train {weights} @ imgsz={imgsz}", flush=True)

        model = YOLO(weights)
        model.train(
            data=str(data_path),
            epochs=epochs,
            imgsz=imgsz,
            seed=seed,
            device=device,
            project=str(runs),
            name=f"train_{index}",
            exist_ok=True,
            **params,
        )

        produced = runs / f"train_{index}" / "weights" / "best.pt"
        if produced.exists():
            target = output / f"best_{index}.pt"
            shutil.move(str(produced), target)
            best_models.append(target)
            print(f"    -> {target}", flush=True)

        del model
        gc.collect()
        torch.cuda.empty_cache()

    if runs.exists():
        shutil.rmtree(runs, ignore_errors=True)

    if not best_models:
        print("Обучение не дало весов", file=sys.stderr)
        return 1

    if not args.no_predict:
        from predict import run_predictions

        run_predictions(
            weights=best_models[0],
            data_yaml=data_path,
            output=HERE / config.get("predict", {}).get("submission", "submission.csv"),
            conf=config.get("predict", {}).get("conf", 0.001),
            iou=config.get("predict", {}).get("iou", 0.7),
            max_det=config.get("predict", {}).get("max_det", 300),
            device=device,
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
