"""AutoFile — inference bundle generated by AutoDetect2.

Runs an ensemble of YOLO checkpoints and fuses their boxes with Weighted Box
Fusion using the parameters found by Optuna on the validation subset:

    python infer.py --images /path/to/test/images
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".bmp", ".webp", ".tif", ".tiff"}
COLUMNS = ["image_id", "class_id", "confidence", "x_center", "y_center", "width", "height"]


def load_params(path: Path) -> dict:
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def extract(model, image: Path, conf: float, device) -> tuple[np.ndarray, np.ndarray, np.ndarray, int, int]:
    result = model.predict(str(image), conf=conf, iou=1.0, max_det=1000, verbose=False, device=device)[0]
    if result.boxes is None or not len(result.boxes):
        return np.empty((0, 4)), np.empty(0), np.empty(0), *result.orig_shape

    boxes = result.boxes.xyxy.cpu().numpy()
    height, width = result.orig_shape
    boxes[:, [0, 2]] /= width
    boxes[:, [1, 3]] /= height
    return boxes, result.boxes.conf.cpu().numpy(), result.boxes.cls.cpu().numpy(), height, width


def main() -> int:
    parser = argparse.ArgumentParser(description="AutoDetect2 inference bundle")
    parser.add_argument("--models", default=str(HERE / "models"), help="Папка с *.pt")
    parser.add_argument("--images", required=True, help="Папка с изображениями")
    parser.add_argument("--params", default=str(HERE / "wbf_params.json"))
    parser.add_argument("--output", default=str(HERE / "submission.csv"))
    parser.add_argument("--device", default="auto")
    args = parser.parse_args()

    import torch
    from ensemble_boxes import weighted_boxes_fusion
    from ultralytics import YOLO

    device = "cuda" if args.device == "auto" and torch.cuda.is_available() else args.device
    if device == "auto":
        device = "cpu"

    params = load_params(Path(args.params))
    model_paths = sorted(Path(args.models).glob("*.pt"))
    if not model_paths:
        raise SystemExit(f"Нет моделей в {args.models}")

    models = [YOLO(str(path)).to(device) for path in model_paths]
    confs = [params["conf"].get(path.name, params.get("conf_default", 0.05)) for path in model_paths]
    weights = [params.get("weights", {}).get(path.name, 1.0) for path in model_paths]
    iou_thr = params.get("wbf_iou", 0.55)
    skip_thr = params.get("skip_box_thr", 0.01)
    conf_type = params.get("conf_type", "avg")

    images = [p for p in sorted(Path(args.images).rglob("*")) if p.suffix.lower() in IMAGE_SUFFIXES]
    if not images:
        raise SystemExit(f"Нет изображений в {args.images}")

    print(f"{len(models)} моделей, {len(images)} изображений, iou={iou_thr}, skip={skip_thr}", flush=True)

    with open(args.output, "w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(COLUMNS)

        for position, image in enumerate(images, start=1):
            boxes_list, scores_list, labels_list = [], [], []
            for model, conf in zip(models, confs):
                boxes, scores, classes, _, _ = extract(model, image, conf, device)
                boxes_list.append(boxes.tolist())
                scores_list.append(scores.tolist())
                labels_list.append(classes.tolist())

            if all(not b for b in boxes_list):
                continue

            fused_boxes, fused_scores, fused_classes = weighted_boxes_fusion(
                boxes_list,
                scores_list,
                labels_list,
                weights=weights,
                iou_thr=iou_thr,
                skip_box_thr=skip_thr,
                conf_type=conf_type,
            )

            for box, score, cls in zip(fused_boxes, fused_scores, fused_classes):
                x1, y1, x2, y2 = box
                writer.writerow(
                    [
                        image.name,
                        int(cls),
                        f"{float(score):.6f}",
                        f"{(x1 + x2) / 2:.6f}",
                        f"{(y1 + y2) / 2:.6f}",
                        f"{x2 - x1:.6f}",
                        f"{y2 - y1:.6f}",
                    ]
                )

            if position % 50 == 0:
                print(f"  {position}/{len(images)}", flush=True)

    print(f"submission: {args.output}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
